//go:build linux

package tun

import (
	"context"
	"fmt"
	"os"
	"os/exec"
	"sync"
	"time"

	"phaethon/util"
)

var (
	dnsMu        sync.Mutex
	dnsMethod    string // "resolved", "nm", "resolvconf"
	dnsBackup    []byte
	dnsBackupPath string
)

// setSystemDNS redirects system DNS to the given TUN IP.
func setSystemDNS(ifaceName, tunIP string) error {
	dnsMu.Lock()
	defer dnsMu.Unlock()

	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()

	if _, err := exec.LookPath("resolvectl"); err == nil {
		if out, err := exec.CommandContext(ctx, "resolvectl", "dns", ifaceName, tunIP).CombinedOutput(); err == nil {
			dnsMethod = "resolved"
			util.LogInfo("tun: systemd-resolved dns for %s set to %s", ifaceName, tunIP)
			return nil
		} else {
			util.LogWarn("tun: resolvectl dns failed, trying next method: %v: %s", err, out)
		}
	}

	if _, err := exec.LookPath("nmcli"); err == nil {
		if out, err := exec.CommandContext(ctx, "nmcli", "device", "modify", ifaceName, "ipv4.dns", tunIP).CombinedOutput(); err == nil {
			dnsMethod = "nm"
			util.LogInfo("tun: NetworkManager dns for %s set to %s", ifaceName, tunIP)
			return nil
		} else {
			util.LogWarn("tun: nmcli dns failed, trying next method: %v: %s", err, out)
		}
	}

	// Fallback: backup /etc/resolv.conf and rewrite
	const resolvConf = "/etc/resolv.conf"
	const backupSuffix = ".phaethon.bak"
	backupPath := resolvConf + backupSuffix

	// If a backup from a previous run still exists, the process likely crashed
	// before restoring. Restore it first so we don't capture TUN-contaminated
	// DNS or overwrite a good backup.
	if _, err := os.Stat(backupPath); err == nil {
		util.LogWarn("tun: stale DNS backup found (previous crash?), restoring first")
		origData, err := os.ReadFile(backupPath)
		if err == nil {
			_ = os.WriteFile(resolvConf, origData, 0644)
		}
		_ = os.Remove(backupPath)
	}

	data, err := os.ReadFile(resolvConf)
	if err != nil {
		return fmt.Errorf("read resolv.conf: %w", err)
	}
	dnsBackup = append([]byte(nil), data...)
	dnsBackupPath = backupPath
	if err := os.WriteFile(dnsBackupPath, data, 0644); err != nil {
		return fmt.Errorf("backup resolv.conf: %w", err)
	}

	newContent := fmt.Sprintf("# Generated by phaethon TUN\nnameserver %s\n", tunIP)
	if err := os.WriteFile(resolvConf, []byte(newContent), 0644); err != nil {
		return fmt.Errorf("write resolv.conf: %w", err)
	}
	dnsMethod = "resolvconf"
	util.LogInfo("tun: resolv.conf dns set to %s", tunIP)
	return nil
}

// restoreSystemDNS restores the system DNS configuration saved by setSystemDNS.
func restoreSystemDNS(ifaceName string) {
	dnsMu.Lock()
	defer dnsMu.Unlock()

	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()

	switch dnsMethod {
	case "resolved":
		if out, err := exec.CommandContext(ctx, "resolvectl", "revert", ifaceName).CombinedOutput(); err != nil {
			util.LogWarn("tun: restore resolved dns fail: %v: %s", err, out)
		} else {
			util.LogInfo("tun: systemd-resolved dns for %s reverted", ifaceName)
		}
	case "nm":
		if out, err := exec.CommandContext(ctx, "nmcli", "device", "modify", ifaceName, "ipv4.dns", "").CombinedOutput(); err != nil {
			util.LogWarn("tun: restore NetworkManager dns fail: %v: %s", err, out)
		} else {
			util.LogInfo("tun: NetworkManager dns for %s restored", ifaceName)
		}
	case "resolvconf":
		if dnsBackupPath == "" {
			return
		}
		if _, err := os.Stat(dnsBackupPath); err != nil {
			util.LogWarn("tun: resolv.conf backup missing, cannot restore")
			return
		}
		data, err := os.ReadFile(dnsBackupPath)
		if err != nil {
			util.LogWarn("tun: read resolv.conf backup fail: %v", err)
			return
		}
		if err := os.WriteFile(dnsBackupPath[:len(dnsBackupPath)-len(".phaethon.bak")], data, 0644); err != nil {
			util.LogWarn("tun: restore resolv.conf fail: %v", err)
			return
		}
		_ = os.Remove(dnsBackupPath)
		util.LogInfo("tun: resolv.conf dns restored")
	}

	dnsMethod = ""
	dnsBackup = nil
	dnsBackupPath = ""
}
