//go:build linux

package tun

import (
	"fmt"
	"net"
	"os"
	"sync"

	"github.com/godbus/dbus/v5"
	"phaethon/util"
)

var (
	dnsMu        sync.Mutex
	dnsMethod    string // "resolved", "nm", "resolvconf"
	dnsBackup    []byte
	dnsBackupPath string
)

// setSystemDNS redirects system DNS to the given TUN IP.
func setSystemDNS(ifaceName, tunIP string) error {
	dnsMu.Lock()
	defer dnsMu.Unlock()

	// Try D-Bus API to systemd-resolved first
	conn, err := dbus.SystemBus()
	if err == nil {
		resolved := conn.Object("org.freedesktop.resolve1", "/org/freedesktop/resolve1")
		
		// Get interface index
		iface, err := net.InterfaceByName(ifaceName)
		if err == nil {
			// Parse DNS IP
			dnsIP := net.ParseIP(tunIP)
			if dnsIP != nil {
				// Call SetLinkDNS(int32 index, array of (int32 family, array of byte address))
				var ipBytes []byte
				var family int32
				if dnsIP.To4() != nil {
					ipBytes = dnsIP.To4()
					family = 2 // AF_INET
				} else {
					ipBytes = dnsIP.To16()
					family = 10 // AF_INET6
				}
				
				// D-Bus signature: a(ii ay) - array of (family, address)
				dnsServers := []struct {
					Family  int32
					Address []byte
				}{
					{Family: family, Address: ipBytes},
				}
				
				call := resolved.Call("org.freedesktop.resolve1.Manager.SetLinkDNS", 0, int32(iface.Index), dnsServers)
				if call.Err == nil {
					dnsMethod = "resolved"
					util.LogInfo("tun: systemd-resolved dns for %s set to %s via D-Bus", ifaceName, tunIP)
					return nil
				} else {
					util.LogWarn("tun: resolved D-Bus SetLinkDNS failed: %v, trying next method", call.Err)
				}
			}
		}
	} else {
		util.LogWarn("tun: D-Bus system bus connection failed: %v", err)
	}

	// Fallback: backup /etc/resolv.conf and rewrite
	const resolvConf = "/etc/resolv.conf"
	const backupSuffix = ".phaethon.bak"
	backupPath := resolvConf + backupSuffix

	// If a backup from a previous run still exists, the process likely crashed
	// before restoring. Restore it first so we don't capture TUN-contaminated
	// DNS or overwrite a good backup.
	if _, err := os.Stat(backupPath); err == nil {
		util.LogWarn("tun: stale DNS backup found (previous crash?), restoring first")
		origData, err := os.ReadFile(backupPath)
		if err == nil {
			_ = os.WriteFile(resolvConf, origData, 0644)
		}
		_ = os.Remove(backupPath)
	}

	data, err := os.ReadFile(resolvConf)
	if err != nil {
		return fmt.Errorf("read resolv.conf: %w", err)
	}
	dnsBackup = append([]byte(nil), data...)
	dnsBackupPath = backupPath
	if err := os.WriteFile(dnsBackupPath, data, 0644); err != nil {
		return fmt.Errorf("backup resolv.conf: %w", err)
	}

	newContent := fmt.Sprintf("# Generated by phaethon TUN\nnameserver %s\n", tunIP)
	if err := os.WriteFile(resolvConf, []byte(newContent), 0644); err != nil {
		return fmt.Errorf("write resolv.conf: %w", err)
	}
	dnsMethod = "resolvconf"
	util.LogInfo("tun: resolv.conf dns set to %s", tunIP)
	return nil
}

// restoreSystemDNS restores the system DNS configuration saved by setSystemDNS.
func restoreSystemDNS(ifaceName string) {
	dnsMu.Lock()
	defer dnsMu.Unlock()

	switch dnsMethod {
	case "resolved":
		// Use D-Bus API to revert DNS
		conn, err := dbus.SystemBus()
		if err == nil {
			resolved := conn.Object("org.freedesktop.resolve1", "/org/freedesktop/resolve1")
			
			// Get interface index
			iface, err := net.InterfaceByName(ifaceName)
			if err == nil {
				// Call RevertLink(int32 index)
				call := resolved.Call("org.freedesktop.resolve1.Manager.RevertLink", 0, int32(iface.Index))
				if call.Err == nil {
					util.LogInfo("tun: systemd-resolved dns for %s reverted via D-Bus", ifaceName)
				} else {
					util.LogWarn("tun: resolved D-Bus RevertLink fail: %v", call.Err)
				}
			} else {
				util.LogWarn("tun: get interface %s index fail: %v", ifaceName, err)
			}
		} else {
			util.LogWarn("tun: D-Bus system bus connection fail: %v", err)
		}
	case "resolvconf":
		if dnsBackupPath == "" {
			return
		}
		if _, err := os.Stat(dnsBackupPath); err != nil {
			util.LogWarn("tun: resolv.conf backup missing, cannot restore")
			return
		}
		data, err := os.ReadFile(dnsBackupPath)
		if err != nil {
			util.LogWarn("tun: read resolv.conf backup fail: %v", err)
			return
		}
		if err := os.WriteFile(dnsBackupPath[:len(dnsBackupPath)-len(".phaethon.bak")], data, 0644); err != nil {
			util.LogWarn("tun: restore resolv.conf fail: %v", err)
			return
		}
		_ = os.Remove(dnsBackupPath)
		util.LogInfo("tun: resolv.conf dns restored")
	}

	dnsMethod = ""
	dnsBackup = nil
	dnsBackupPath = ""
}
